# watining for eslint rewrite and flat config implementation
# https://github.com/eslint/eslint/issues/13481
# https://github.com/microsoft/vscode-eslint/issues/1518

root: true
ignorePatterns:
  - .eslintrc.cjs
env:
  browser: true
  es2022: true
  node: true

parser: '@typescript-eslint/parser'

extends:
  # - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript

parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: true

plugins:
  - "@typescript-eslint"

settings:
  import/resolver:
    typescript: true
    node: true

  import/parsers:
    "@typescript-eslint/parser": [ .ts, .tsx ]

rules:
  indent:
    - warn
    - 3
  linebreak-style:
    - warn
    - unix
  quotes:
    - warn
    - double
  semi:
    - error
    - never
  "@typescript-eslint/consistent-type-exports": warn
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/no-import-type-side-effects": warn
  import/order:
    - warn
    - newlines-between: always
  import/no-deprecated: warn
